import Head from 'next/head'
import ContactForm from '../components/ContactForm'
import { Suspense, useRef, useState } from 'react'
import { AnimatePresence, motion as m } from "framer-motion"
import { Canvas, useFrame } from '@react-three/fiber'
import { OrbitControls } from '@react-three/drei'
import { Mesh } from 'three'

function Thing() {
  const ref = useRef<Mesh>(null!)
  useFrame(() => (ref.current.rotation.x = ref.current.rotation.y += 0.01))
  return (
    <mesh
      ref={ref}
      onClick={e => console.log('click')}
      onPointerOver={e => console.log('hover')}
      onPointerOut={e => console.log('unhover')}>
      <boxBufferGeometry attach="geometry" args={[1, 1, 1]} />
      <meshNormalMaterial attach="material" />
    </mesh>
  )
}

export default function Home() {
  const [blur, setBlur] = useState(false)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AnimatePresence key={"mainAnimation"}>
        <m.div
          key={"backgroundOverlay"}
          initial={{ opacity: 0, }}
          animate={{ opacity: 0.7, }}
          exit={{
            opacity: 0,
            transition: {
              duration: 3,
              ease: "easeInOut"
            }
          }}
          transition={{
            duration: 30,
            ease: "easeInOut"
          }}
          className={`${blur ? "bg-black" : ""}  absolute h-screen w-screen `} />
        <div className='flex justify-center items-center align-middle h-screen w-screen bg-slate-600'>
          <ContactForm blurBackground={setBlur} />
          <h1 className='absolute h-screen w-screen flex justify-center items-start pt-96'>hello</h1>
          <div className='absolute h-screen w-screen'>
            <Canvas>
              <Suspense fallback={null}>
                <Thing />
                <OrbitControls />
              </Suspense>
            </Canvas>
          </div>
        </div>
      </AnimatePresence>
    </>
  )
}
