import Head from 'next/head'
import { Inter } from '@next/font/google'
import ContactForm from '../components/ContactForm'
import { useState } from 'react'
import { AnimatePresence, motion as m, Variants } from "framer-motion"
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [blur, setBlur] = useState(false)
  return (
    <AnimatePresence>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex z-0  flex-col justify-center items-center h-screen w-screen bg-slate-600'>
        <h1 className='absolute top-[600px]'>hello</h1>
        <div className={`flex flex-col justify-center items-center   z-10`}>
          <m.div initial={{ opacity: 0 }}
            animate={{ opacity: 0.5 }}
            exit={{
              opacity: 0,
              transition: {
                duration: 3,
                ease: "easeInOut"
              }
            }}
            transition={{
              duration: 1,
              ease: "easeInOut"
            }}
            className={`${blur ? "bg-black" : ""} absolute w-screen h-screen z-0`}></m.div>
          <ContactForm blurBackground={setBlur} />

        </div>
      </div>
    </AnimatePresence>
  )
}
